const {
    AttachmentBuilder,
    ChannelType
} = require('discord.js');
const config = require('../config');

function isTicketChannel(channel) {
    return Boolean(channel?.name) && (
        channel.name.startsWith('ticket-') ||
        channel.name.startsWith('closed-') ||
        channel.name.startsWith('trade-')
    );
}

function getTicketEntryByChannel(configManager, channelId) {
    return Array.from(configManager.tickets.entries()).find(([, ticket]) => ticket.channelId === channelId) || null;
}

function getTicketSummary(ticketData, channel) {
    return {
        ownerId: ticketData?.userId || null,
        ownerTag: ticketData?.userTag || 'Unknown',
        robloxUsername: ticketData?.robloxUsername || 'Unknown',
        buying: ticketData?.buying || 'Unknown',
        game: ticketData?.game || 'Unknown',
        channelName: channel?.name || 'unknown-channel'
    };
}

async function resolveTicketSummary(configManager, channel) {
    const ticketEntry = getTicketEntryByChannel(configManager, channel.id);
    if (ticketEntry) {
        return getTicketSummary(ticketEntry[1], channel);
    }

    const messages = await channel.messages.fetch({ limit: 100 });
    const ticketMessage = Array.from(messages.values())
        .sort((a, b) => a.createdTimestamp - b.createdTimestamp)
        .find(message => message.embeds.some(embed => 
            embed.title === '🎫 New Ticket' || embed.title === '🤝 New Trade Session'
        ));

    if (!ticketMessage) {
        return getTicketSummary(null, channel);
    }

    const embed = ticketMessage.embeds.find(entry => 
        entry.title === '🎫 New Ticket' || entry.title === '🤝 New Trade Session'
    );
    const isTrade = embed.title === '🤝 New Trade Session';
    const fields = Object.fromEntries((embed?.fields || []).map(field => [field.name, field.value]));
    
    const ownerValue = isTrade ? embed.description.split('\n')[0] : (fields['Ticket Owner'] || fields['Discord'] || '');
    const sellerValue = isTrade ? embed.description.split('\n')[1] : null;

    const ownerIdMatch = ownerValue.match(/<@(\d+)>/);
    const ownerTagMatch = ownerValue.match(/\(([^)]+)\)/);
    const sellerIdMatch = sellerValue?.match(/<@(\d+)>/);

    return {
        ownerId: ownerIdMatch?.[1] || null,
        ownerTag: ownerTagMatch?.[1] || 'Unknown',
        robloxUsername: fields['Roblox User'] || 'Unknown',
        buying: fields['Buying'] || 'Unknown',
        game: fields['Game'] || 'Unknown',
        channelName: channel?.name || 'unknown-channel',
        sellerId: sellerIdMatch?.[1] || null,
        isTrade: isTrade
    };
}

async function fetchTranscriptMessages(channel) {
    const allMessages = [];
    let before;

    while (true) {
        const options = { limit: 100 };
        if (before) {
            options.before = before;
        }

        const batch = await channel.messages.fetch(options);
        if (batch.size === 0) {
            break;
        }

        const batchMessages = Array.from(batch.values()).sort((a, b) => b.createdTimestamp - a.createdTimestamp);
        allMessages.push(...batchMessages);
        before = batchMessages[batchMessages.length - 1].id;

        if (batchMessages.length < 100) {
            break;
        }
    }

    return allMessages.sort((a, b) => a.createdTimestamp - b.createdTimestamp);
}

function buildTranscriptContent(channel, messages, generatedByTag, ticketData) {
    const summary = getTicketSummary(ticketData, channel);
    const transcriptLines = [
        `TRANSCRIPT FOR ${summary.channelName}`,
        `Generated: ${new Date().toISOString()}`,
        `Generated by: ${generatedByTag}`,
        `Ticket Owner: ${summary.ownerTag}${summary.ownerId ? ` (${summary.ownerId})` : ''}`,
        `Roblox Username: ${summary.robloxUsername}`,
        `Buying: ${summary.buying}`,
        `Game: ${summary.game}`,
        '=====================================',
        ''
    ];

    for (const message of messages) {
        const timestamp = message.createdAt.toISOString();
        const author = message.author?.tag || 'Unknown User';
        const content = message.content?.trim() || '[No text]';
        const attachments = message.attachments.size > 0
            ? ` [Attachments: ${message.attachments.map(attachment => attachment.url).join(', ')}]`
            : '';

        transcriptLines.push(`[${timestamp}] ${author}: ${content}${attachments}`);

        if (message.embeds.length > 0) {
            for (const embed of message.embeds) {
                transcriptLines.push(`[Embed: ${embed.title || 'No title'}]`);
            }
        }
    }

    transcriptLines.push('');
    return transcriptLines.join('\n');
}

async function createTranscript(channel, ticketData, generatedByTag) {
    const messages = await fetchTranscriptMessages(channel);
    const transcript = buildTranscriptContent(channel, messages, generatedByTag, ticketData);
    const fileName = `transcript-${channel.name}-${Date.now()}.txt`;
    const fileBuffer = Buffer.from(transcript, 'utf-8');

    return { fileName, fileBuffer };
}

async function incrementCounterChannel(guild, channelId) {
    const counterChannel = guild.channels.cache.get(channelId);

    if (!counterChannel || typeof counterChannel.setName !== 'function') {
        return { updated: false, reason: 'channel_not_found' };
    }

    const currentName = counterChannel.name || '';
    const match = currentName.match(/(\d+)(?!.*\d)/);

    if (!match) {
        return { updated: false, reason: 'number_not_found', channelName: currentName };
    }

    const currentValue = Number.parseInt(match[1], 10);
    const nextValue = currentValue + 1;
    const updatedName = `${currentName.slice(0, match.index)}${nextValue}${currentName.slice(match.index + match[1].length)}`;

    await counterChannel.setName(updatedName, 'Order completed with /done');

    return {
        updated: true,
        previousValue: currentValue,
        nextValue,
        previousName: currentName,
        updatedName
    };
}

function buildTranscriptAttachment(fileName, fileBuffer) {
    return new AttachmentBuilder(fileBuffer, { name: fileName });
}

function removeTicketByChannel(configManager, channelId) {
    const ticketEntry = getTicketEntryByChannel(configManager, channelId);

    if (!ticketEntry) {
        return null;
    }

    const [userId, ticketData] = ticketEntry;
    configManager.closeTicket(userId);

    return { userId, ticketData };
}

async function deleteConnectedChannels(channel, configManager) {
    const guildConfig = config.system;
    const pilotCategoryId = guildConfig?.pilotChannelId || null;
    const cleanName = channel.name.replace('closed-', '').replace('ticket-', '');

    const connectedChannels = channel.guild.channels.cache.filter(candidate => {
        if (candidate.id === channel.id || candidate.type !== ChannelType.GuildText) {
            return false;
        }

        if (pilotCategoryId && candidate.parentId !== pilotCategoryId) {
            return false;
        }

        return candidate.name.includes(cleanName);
    });

    let deletedCount = 0;
    for (const [, connectedChannel] of connectedChannels) {
        try {
            await connectedChannel.delete('Connected ticket deleted');
            deletedCount++;
        } catch (error) {
            console.error(`Failed to delete connected channel ${connectedChannel.name}:`, error);
        }
    }

    return deletedCount;
}

module.exports = {
    buildTranscriptAttachment,
    createTranscript,
    deleteConnectedChannels,
    getTicketEntryByChannel,
    getTicketSummary,
    incrementCounterChannel,
    isTicketChannel,
    removeTicketByChannel,
    resolveTicketSummary
};
